# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200517_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('OF', 'Offer'), ('NW', 'New')], default='', max_length=2),
        ),
    ]
